fc_npy_path: data/pretrain/fc.npy
save_encoder_path: checkpoints/pretrain/brainnetgfm_pretrain.pt
save_model_mode: full
roi_mni_path: data/roi/roi_mni.xlsx
train_ratio: 0.8
batch_size_per_gpu: 64
num_epochs: 100
lr: 0.0005
weight_decay: 0.00001
seed: 42
num_workers: 8
pin_memory: true
topk_ratio: 0.1
fisher_z: null
use_abs_for_topk: true
alpha_recon: 1.0
beta_cl: 1.0
mask_ratio_node: 0.5
mask_ratio_edge: 0.5
edge_loss_weight: 1.0
sce_gamma: 2.0
drop_node_ratio: 0.3
drop_edge_ratio: 0.3
feat_mask_ratio: 0.3
temperature: 0.25
gnn_hidden_dim: 256
proj_dim: 256
recon_hidden_dim: 256
num_gnn_layers: 3
num_decoder_layers: 1
dropout: 0.2
transformer_heads: 4
max_grad_norm: 3.0
ddp_backend: nccl
use_graph_attr: true
pe_type: rw
pe_dim: 256
jk_mode: concat
node_norm_type: layernorm
node_mask_edge_mode: token
recon_target_mode: full
recon_topk_ratio: 0.3
recon_proj_dim: 128
recon_loss_type: sce+mse
node_cl_cross_subject_weight: 0.2
contrastive_loss_type: nt_xent
